version: '3.1'
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - nginx_with_others
      
networks:
  nginx_with_others:
    external: true