version: '3.1'
services:
  nginx_host:
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - nginx_with_others
    volumes:
      - "/home/chwech/docker/nginx/nginx.conf:/etc/nginx/conf.d"
      - "/home/chwech/docker/nginx/static:/static"      
networks:
  nginx_with_others:
    external: true
