version: '3.1'
services:
  nginx:
    build: .
    ports:
      - "80:80"
    networks:
      - nginx_with_others
    external_links:
      - wordpress

networks:
  nginx_with_others:
    external: true